image: python:3.7

before_script:
  - pip install tox

stages:
  - style
  - build
  - test
  - documentation

# style
style:
  stage: style
  image: python:3.7
  script:
    - tox -vv
  variables:
    TOXENV: flake8,black

# build
build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# test
py37:linux:
  stage: test
  script:
    - tox -vv
  image: python:3.7
  variables:
    TOXENV: py37

# documentation
pages:
  stage: documentation
  before_script:
    - echo "documentation"
  script:
    - pip install -e .
    - cd docs
    - pip install -r requirements.txt
    - make html
    - mv _build/html ../public
    - cd ..
  artifacts:
    paths:
      - public
  only:
    - master