#name: Deply to GitHub Container Registry
#on: [ push ]
#  branches: [ main ]
#
#jobs:
#  publish-hello-docker-image:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout sources
#      uses: actions/checkout@v2
#
#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#
#    - name: Build the container image
#      run: |
#      docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
#      docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
#      docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
